import { writeFileSync, readdirSync, statSync } from "fs";
import { join } from "path";

const DIST_DIR = "dist/client";
const PUBLIC_DIR = "public";

function getFiles(dir: string, baseDir: string = dir): string[] {
  let results: string[] = [];
  const list = readdirSync(dir);
  for (const file of list) {
    const path = join(dir, file);
    const stat = statSync(path);
    if (stat && stat.isDirectory()) {
      results = results.concat(getFiles(path, baseDir));
    } else {
      // Create relative URL
      results.push("/" + path.replace(baseDir + "/", "").replace(/\\/g, "/"));
    }
  }
  return results;
}

try {
  // 1. Get all assets from dist/client/assets
  const assets = getFiles(join(DIST_DIR, "assets")).filter((f) => !f.endsWith(".map"));

  // 2. Add core public assets
  const publicAssets = [
    "/manifest.webmanifest",
    "/favicon.png",
    "/icon-192.png",
    "/icon-512.png",
    "/icon-maskable-512.png",
  ];

  // 3. Add local fonts
  const fonts = getFiles(join(PUBLIC_DIR, "fonts"));

  const allPrecachable = ["/", ...publicAssets, ...fonts, ...assets];

  writeFileSync(
    join(PUBLIC_DIR, "sw-precache.js"),
    `/* Generated by scripts/generate-precache.ts */\nself.PRECACHE_ASSETS = ${JSON.stringify(allPrecachable, null, 2)};`,
  );

  console.log(`Generated sw-precache.js with ${allPrecachable.length} assets.`);
} catch (e) {
  console.error("Failed to generate precache manifest:", e);
  // Fallback to minimal list if build output isn't available yet
  writeFileSync(
    join(PUBLIC_DIR, "sw-precache.js"),
    `self.PRECACHE_ASSETS = ["/", "/manifest.webmanifest"];`,
  );
}
