import { writeFileSync, readdirSync, statSync, existsSync } from "fs";
import { join, relative } from "path";
import { getBuildOutputDir, validateOutputDir } from "./build-utils";

const PUBLIC_DIR = "public";
const OUTPUT_DIR = getBuildOutputDir();

/** Returns web URLs (rooted at the served origin) for every file under `dir`. */
function getFiles(dir: string, baseDir: string): string[] {
  let results: string[] = [];
  if (!existsSync(dir)) return results;
  const list = readdirSync(dir);
  for (const file of list) {
    const path = join(dir, file);
    const stat = statSync(path);
    if (stat && stat.isDirectory()) {
      results = results.concat(getFiles(path, baseDir));
    } else {
      // Create a root-relative URL (e.g., /assets/foo.js)
      const relPath = relative(baseDir, path);
      results.push("/" + relPath.replace(/\\/g, "/"));
    }
  }
  return results;
}

try {
  validateOutputDir(OUTPUT_DIR);

  // Scan the actual production output
  const allFiles = getFiles(OUTPUT_DIR, OUTPUT_DIR);

  // Filter and normalize
  const allPrecachable = allFiles.filter((f) => {
    // Exclude the manifest itself and source maps
    if (f === "/sw-precache.js") return false;
    if (f.endsWith(".map")) return false;
    return true;
  });

  // Always include the root for the PWA shell
  if (!allPrecachable.includes("/")) {
    allPrecachable.unshift("/");
  }

  const contents = `/* Generated by scripts/generate-precache.ts — do not edit. */\nself.PRECACHE_ASSETS = ${JSON.stringify(allPrecachable, null, 2)};\n`;

  const outputPath = join(OUTPUT_DIR, "sw-precache.js");
  writeFileSync(outputPath, contents);

  console.log(`Generated ${outputPath}: ${allPrecachable.length} entries.`);
} catch (error: unknown) {
  const message = error instanceof Error ? error.message : String(error);
  console.error(`Error: ${message}`);
  process.exit(1);
}
