import { writeFileSync, readdirSync, statSync, existsSync } from "fs";
import { join } from "path";

const DIST_DIR = "dist/client";
const PUBLIC_DIR = "public";

/** Returns web URLs (rooted at the served origin) for every file under `dir`. */
function getFiles(dir: string, rootDir: string): string[] {
  let results: string[] = [];
  if (!existsSync(dir)) return results;
  const list = readdirSync(dir);
  for (const file of list) {
    const path = join(dir, file);
    const stat = statSync(path);
    if (stat && stat.isDirectory()) {
      results = results.concat(getFiles(path, rootDir));
    } else {
      results.push("/" + path.slice(rootDir.length + 1).replace(/\\/g, "/"));
    }
  }
  return results;
}

// Emitted build assets (hashed JS/CSS) — only what the build genuinely produced.
const buildAssets = getFiles(join(DIST_DIR, "assets"), DIST_DIR).filter((f) => !f.endsWith(".map"));

// Static files shipped from public/ that actually exist on disk.
const staticCandidates = [
  "/manifest.webmanifest",
  "/favicon.png",
  "/icon-192.png",
  "/icon-512.png",
  "/icon-maskable-512.png",
];
const staticAssets = staticCandidates.filter((p) => existsSync(join(PUBLIC_DIR, p.slice(1))));
const fonts = getFiles(join(PUBLIC_DIR, "fonts"), PUBLIC_DIR);

// "/" is the navigation shell. We never precache "/index.html" — the production
// output does not contain that file.
const allPrecachable = ["/", ...staticAssets, ...fonts, ...buildAssets];

const contents = `/* Generated by scripts/generate-precache.ts — do not edit. */\nself.PRECACHE_ASSETS = ${JSON.stringify(allPrecachable, null, 2)};\n`;

writeFileSync(join(PUBLIC_DIR, "sw-precache.js"), contents);
// The script runs after `vite build`, so mirror it into the emitted output too.
if (existsSync(DIST_DIR)) writeFileSync(join(DIST_DIR, "sw-precache.js"), contents);

console.log(
  `Generated sw-precache.js: ${allPrecachable.length} entries (${buildAssets.length} build assets).`,
);
